### ISSUE TITLE
How to get all pages into the pages folder fully html rendered ?

### ISSUE THREAD

**Issue by peio72** [danielroe/nuxt-full-static#20]
### 📚 What are you trying to do?

I would like to have all my pages generated prerendered and full html

**Comment by peio72** [comment]
I currently only have the index full html all other pages/routes as spa

**Comment by danielroe** [comment]
Would you be able to prepare a reproduction from https://stackblitz.com/github/danielroe/nuxt-full-static/tree/main/playground ?

**Comment by danielroe** [comment]
(Discussed on Discord and it seems there was no issue.)
