### ISSUE TITLE
fix: it work only with external url

### ISSUE THREAD

**Issue by max5432112345** [danielroe/nuxt-full-static#35]
### 🐛 The bug

It work only with external url
Work
```
const data = await useFetch('https://jsonplaceholder.typicode.com/posts', {
  transform: posts => posts.slice(0, 10),
})
```

Local not work, return html of index page
```
const data2 = await useFetch('http://localhost:3000/api/test', {
  transform: posts => posts.slice(0, 10),
})
```

### 🛠️ To reproduce
https://github.com/max5432112345/nuxt-error3
---

### 🌈 Expected behaviour

---

**Comment by max5432112345** [comment]
And nuxt generate say that page index not found.
>  ├─ /index (30ms) (Error: [404] Page not found: /index)    
> ├─ /en/index (41ms) (Error: [404] Page not found: /en/index)    

And 302 redirect (but in spa for that routes i get 404) for pages without language in path
>   ├─ /login (82ms) (Error: [302] )  

And page/error.vue also throw errors, say something about status code
> [nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'statusCode')                                                                     16:21:40

  ├─ /api/_static/ro/error.json (21ms)     
  
```
<template>
  <button @click="handleError">Clear errors</button>
</template>

<script setup lang="ts">
import { defineProps } from '#app'
import { definePageMeta } from '#imports'

definePageMeta({
  layout: 'error'
})

const props = defineProps({
  error: Object
})

const handleError = () => clearError({
  redirect: {
    name: 'index'
  }
})
</script> 

```

And I see frond page for second and other the page what is needed (in your playground is the same)

**Comment by max5432112345** [comment]
And I use it with i18n module

**Comment by max5432112345** [comment]
and I started to read svelte but its server part is also shit with it's layouts, pluses, ts, svelt all in routes. 
nest is nice. please replace nitro with nest :)

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by max5432112345** [comment]
@danielroe https://github.com/max5432112345/nuxt-error3

**Comment by n4an** [comment]
@danielroe  not work when fetch api ($fetch('/api/test')) and refresh page you will get html of index page and not json

**Comment by n4an** [comment]
http://localhost:3000/favicon.ico return home page and after 404 error

**Comment by danielroe** [comment]
@n4an If you want your API to be available, you will need to run `nuxi build` rather than `nuxi generate`.
