### ISSUE TITLE
help: Running Nitro alongside the static site

### ISSUE THREAD

**Issue by simoneldevig** [danielroe/nuxt-full-static#43]
### 📚 What are you trying to do?

Hi!

I've tested this package out for my server-side rendered Nuxt 3 app and it works great!

My only issue is that I have some Nitro API's that is being requested at runtime, so I wonder if it would be possible to generate both a static site and build the Nitro API's as well and then be able to serve both with `yarn start`? :-) 

### 🔍 What have you tried?

`yarn generate` --> only static files generated
`yarn build` --> only SSR site generated

### ℹ️ Additional context

The goal is to have a Nuxt 3 site running statically on Netlify while still have my API's available as functions for client-side requests.

**Comment by danielroe** [comment]
You should be able to use `nuxi build` with a list of routes to prerender. For example, this config will prerender the listed routes and render everything else (e.g. api routes) dynamically.

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  nitro: {
    prerender: {
      routes: ['/', '/about']
    }
  }
})
```

**Comment by simoneldevig** [comment]
Aah cool - didn't know I could configure it via the Nitro config.

Thanks for clarifying 💪
